apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: employee
  labels:
    app: "api"
spec:
  selector:
    matchLabels:
      app: "api"
  replicas: 2
  template:
    metadata:
      labels:
        app:  "api"
    spec:
      containers:
      - name: "api"
        image: "registry.digitalocean.com/salacyber/employee-api:uat-7"
        # resources:
          #   requests:
          #     memory: "400Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "800Mi"
          #     cpu: "800m"
        ports:
        - containerPort: 4000
        env:
          - name: CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: CONNECTION_STRING
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: DB_NAME
      restartPolicy: Always
