apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: employee
spec:
  selector:
    app: api
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000
